env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  # Style
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never

  # Possible Errors
  no-extra-parens:
    - off

  # Best Pracises
  array-callback-return:
    - warn
  block-scoped-var:
    - off
  complexity:
    - error
    - 5
  consistent-return:
    - error
  curly:
    - warn
    - multi-line
  dot-location:
    - error
    - object


